title: مشاهدات حسین فیروز
motto: پسری که همیشه میخندد :)
author: حسین فیروز
email: hsnfirooz@yahoo.com
url: https://hsnfirooz.com # the base hostname & protocol for your site
baseurl: # the subpath of your site, e.g. /blog
keywords: کامپیوتر بلاگ وب فارسی روزنوشته کتاب
copyright: "Commons Attribution 4.0 International"
robot:
description: > # this means to ignore newlines
  در اینجا مشاهدات و یادداشت‌های شخصی‌ام را مینویسم.
long_description: >
  تمامی نوشته‌ها به راحتی از صفحه گیت‌هاب قابل دسترسی هستند. ذکر منبع موجب دلگرمی نویسنده و نشانه‌ی اخلاق حرفه‌ای است.

favicon: assets/img/favicon.png
permalink: :title.html
timezone: Asia/Tehran

theme: jekyll-theme-mehdix-rtl

paginate: 10
paginate_path: /page:num/

tag_page_layout: tag_page
tag_page_dir: tag

collections:
  projects:
    output: true

comment_system: static # or disqus. Default is no comments.
#disqus_shortname: mehdix
#google_analytics_id: UA-57282325-1
#feedburner_id: REPLACE_WITH_YOUR_FEEDBURNER_ID

lang: fa_IR
#twitter:
  #username: mehdisadeghii
github:
  username: hsnfirooz
  repository: hsnfirooz.com
# Footer logo will disappear if not set.
#logo: assets/img/me.png

exclude:
- scripts
- cache
- .bundle
- .sass-cache
- reply-mail-hook
- vendor
- CONTRIBUTING.md
- netlify.toml
- wercker.yml
- LICENSE
- env.sh
- screenshot.png
- jekyll-theme-mehdix-rtl.sublime-project
- jekyll-theme-mehdix-rtl.sublime-workspace
- travis.yml
- jekyll-theme-mehdix-rtl.gemspec
- rebuild_comments.py
- README.md
- Gemfile
- Gemfile.lock
